### ISSUE TITLE
GetItemType HelperMethod

### ISSUE THREAD

**Issue by rcairnc** [jp-slackspace/x-tension-c-sharp#3]
Hello,

Although this works as described, the API has been since updated and can now return the item category, e.g 'Picture', 'Audio/video' and the file format consistency by combining the buffer length with some flags:

API documentation: 

> nBufferLenAndFlags contains the length of the buffer that lpTypeDescr points to in the lower word, measured in characters, and in v18.9 and later may be optionally combined with one of the below flags.
> 
> 0x20000000: receive a textual description of the file type instead (e.g. “JPEG” or “Dynamic-Link Library”)
> 0x40000000: receive a textual designation of the category that the file type belongs to instead (e.g. “Pictures” or “Programs”)
> 0x80000000: receive type status as usual in the lowest byte, but file format consistency in the second-lowest byte (0=unknown, 1=OK, 2=irregular), v19.3 and later

**Comment by slackspace-lab** [comment]
Fixed. Thanks for reporting!
